version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
      - dependency-name: "eslint*"
      - dependency-name: "babel-eslint"
      - dependency-name: "js-yaml"
      - dependency-name: "*prettier*"
  rebase-strategy: disabled
