# Set update schedule for GitHub Actions only

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - 'dependencies'
    rebase-strategy: disabled
