version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@popperjs/core"
    versions:
    - 2.8.2
    - 2.8.6
  - dependency-name: vue-eslint-parser
    versions:
    - 7.5.0
  rebase-strategy: disabled
